### ISSUE TITLE
WebGL?

### ISSUE THREAD

**Issue by starkoracles** [MarcoCiaramella/sha256-gpu#3]
Hi @MarcoCiaramella , I noticed that lots of browsers don’t have web GPU enabled yet (safari, chrome on iOS) I’m wondering if you’ve stumbled upon a good example on how to do a similar thing using WebGL?

**Comment by MarcoCiaramella** [comment]
hello @starkoracles !
There are no other APIs for GPGPU on browser. WebGL doesn't support GPGPU because it is a graphics API only. But there was a try by W3C community to bring OpenCL (WebCL) to browser but it failed. The only API with GPGPU capabilities is WebGPU released this April for Chromium based browser. Hope in the next months all browsers will implement this API!

**Comment by starkoracles** [comment]
Thanks! I looked at a few WebGL examples (not deeply enough), and I’m wondering what blocks calculating hashes, do you have a concrete example?

**Comment by MarcoCiaramella** [comment]
@starkoracles as said above WebGL doesn't have a pure GPGPU capabilites. Yes you can still do GPGPU using some workarounds but it is meaningless because the performance are very bad and data buffer to pass as "uniform" have a limited size.

**Comment by MarcoCiaramella** [comment]
@starkoracles if you are looking for an example I think you can find something on github but in practice it is better collapse the sha256 computation on CPU when WebGPU is not available.

**Comment by starkoracles** [comment]
That’s super helpful, thanks! Do you know what’s the underlying reason for that? Is it because the WebGL compiler isn’t good for that?

**Comment by MarcoCiaramella** [comment]
the architecture of WebGL (OpenGL) pipeline is specific for graphics. It has two types of buffer for input data. "Attribute buffer" for vertex attributes and "Uniform" for generic data. The first one has an unlimited size, the second one has a limit in size. For sha256 both of them are useless because the first one will be interpolated and the second one is too small for messages to hash compared to processing units available because uniform buffer are no intended for parallelism.
If you cannot find an example using a specific technology is because you cannot ;)

**Comment by starkoracles** [comment]
@MarcoCiaramella thanks for the context, this is awesome to know!

**Comment by starkoracles** [comment]
@MarcoCiaramella did you happen to find a good way to test specific functions? Or you only tested it as a whole?

**Comment by MarcoCiaramella** [comment]
@starkoracles what do you mean for specific functions?

**Comment by starkoracles** [comment]
If there are specific sub routines that you want to test their logic? I assume you can create a new compute pipeline to just hit them, but I’m wondering if there is something simpler
